"""Add execution fields

Revision ID: 08a36fd68478
Revises: f36236e1548e
Create Date: 2026-02-17 16:41:37.035416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a36fd68478'
down_revision: Union[str, Sequence[str], None] = 'f36236e1548e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('error_message', sa.String(length=2000), nullable=True))
    op.add_column('executions', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('executions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('node_executions', sa.Column('output', sa.JSON(), nullable=True))
    op.add_column('node_executions', sa.Column('error_message', sa.String(length=2000), nullable=True))
    op.add_column('node_executions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('node_executions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node_executions', 'updated_at')
    op.drop_column('node_executions', 'created_at')
    op.drop_column('node_executions', 'error_message')
    op.drop_column('node_executions', 'output')
    op.drop_column('executions', 'updated_at')
    op.drop_column('executions', 'started_at')
    op.drop_column('executions', 'error_message')
    # ### end Alembic commands ###
