"""Initial migration

Revision ID: 1227f4ecab01
Revises: 
Create Date: 2026-02-17 12:04:50.635896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1227f4ecab01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('members', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_teams'))
    )
    op.create_index(op.f('ix_agent_teams_id'), 'agent_teams', ['id'], unique=False)
    op.create_index(op.f('ix_agent_teams_name'), 'agent_teams', ['name'], unique=True)
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('system_prompt', sa.String(length=5000), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('capability_ids', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('source', sa.Enum('GLOBAL', 'PLUGIN', 'PROJECT', name='skillsource', native_enum=False), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills'))
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflows'))
    )
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_index(op.f('ix_workflows_name'), 'workflows', ['name'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('project_path', sa.String(length=500), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('agent_team_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'WAITING_USER', 'SUCCEEDED', 'FAILED', name='taskstatus', native_enum=False), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_tasks_workflow_id_workflows')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('workflow_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('TASK', 'DECISION', 'PARALLEL_GATEWAY', name='workflownodetype', native_enum=False), nullable=False),
    sa.Column('agent_team_id', sa.Integer(), nullable=True),
    sa.Column('preferred_agent_ids', sa.JSON(), nullable=False),
    sa.Column('capability_filter_ids', sa.JSON(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('position_x', sa.Integer(), nullable=True),
    sa.Column('position_y', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_workflow_nodes_workflow_id_workflows')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_nodes'))
    )
    op.create_index(op.f('ix_workflow_nodes_id'), 'workflow_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_nodes_workflow_id'), 'workflow_nodes', ['workflow_id'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='executionstatus', native_enum=False), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_executions_task_id_tasks')),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_executions_workflow_id_workflows')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executions'))
    )
    op.create_index(op.f('ix_executions_id'), 'executions', ['id'], unique=False)
    op.create_index(op.f('ix_executions_status'), 'executions', ['status'], unique=False)
    op.create_index(op.f('ix_executions_task_id'), 'executions', ['task_id'], unique=False)
    op.create_table('workflow_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('from_node_id', sa.Integer(), nullable=False),
    sa.Column('to_node_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['from_node_id'], ['workflow_nodes.id'], name=op.f('fk_workflow_edges_from_node_id_workflow_nodes')),
    sa.ForeignKeyConstraint(['to_node_id'], ['workflow_nodes.id'], name=op.f('fk_workflow_edges_to_node_id_workflow_nodes')),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_workflow_edges_workflow_id_workflows')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_edges'))
    )
    op.create_index(op.f('ix_workflow_edges_id'), 'workflow_edges', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_edges_workflow_id'), 'workflow_edges', ['workflow_id'], unique=False)
    op.create_table('node_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='executionstatus', native_enum=False), nullable=False),
    sa.Column('logs_path', sa.String(length=500), nullable=True),
    sa.Column('output_summary', sa.String(length=2000), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_node_executions_execution_id_executions')),
    sa.ForeignKeyConstraint(['node_id'], ['workflow_nodes.id'], name=op.f('fk_node_executions_node_id_workflow_nodes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_executions'))
    )
    op.create_index(op.f('ix_node_executions_execution_id'), 'node_executions', ['execution_id'], unique=False)
    op.create_index(op.f('ix_node_executions_id'), 'node_executions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_executions_id'), table_name='node_executions')
    op.drop_index(op.f('ix_node_executions_execution_id'), table_name='node_executions')
    op.drop_table('node_executions')
    op.drop_index(op.f('ix_workflow_edges_workflow_id'), table_name='workflow_edges')
    op.drop_index(op.f('ix_workflow_edges_id'), table_name='workflow_edges')
    op.drop_table('workflow_edges')
    op.drop_index(op.f('ix_executions_task_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_status'), table_name='executions')
    op.drop_index(op.f('ix_executions_id'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_workflow_nodes_workflow_id'), table_name='workflow_nodes')
    op.drop_index(op.f('ix_workflow_nodes_id'), table_name='workflow_nodes')
    op.drop_table('workflow_nodes')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_workflows_name'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_agent_teams_name'), table_name='agent_teams')
    op.drop_index(op.f('ix_agent_teams_id'), table_name='agent_teams')
    op.drop_table('agent_teams')
    # ### end Alembic commands ###
