"""Add advanced workflow features

Revision ID: 33de4c399788
Revises: c3b40ac3ce76
Create Date: 2026-02-17 17:39:55.554534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33de4c399788'
down_revision: Union[str, Sequence[str], None] = 'c3b40ac3ce76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_nodes', sa.Column('condition_expression', sa.String(length=500), nullable=True))
    op.add_column('workflow_nodes', sa.Column('loop_condition', sa.String(length=500), nullable=True))
    op.add_column('workflow_nodes', sa.Column('max_iterations', sa.Integer(), nullable=True))
    op.add_column('workflow_nodes', sa.Column('parallel_mode', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_nodes', 'parallel_mode')
    op.drop_column('workflow_nodes', 'max_iterations')
    op.drop_column('workflow_nodes', 'loop_condition')
    op.drop_column('workflow_nodes', 'condition_expression')
    # ### end Alembic commands ###
