"""add agent session fields to execution

Revision ID: 554752830809
Revises: 56ca36338846
Create Date: 2026-03-02 01:10:54.225053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '554752830809'
down_revision: Union[str, Sequence[str], None] = '56ca36338846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('session_id', sa.String(length=100), nullable=True))
    op.add_column('executions', sa.Column('last_activity_at', sa.DateTime(), nullable=True))
    op.add_column('executions', sa.Column('is_background', sa.Boolean(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_executions_session_id'), 'executions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_executions_session_id'), table_name='executions')
    op.drop_column('executions', 'is_background')
    op.drop_column('executions', 'last_activity_at')
    op.drop_column('executions', 'session_id')
    # ### end Alembic commands ###
