"""Add terminal execution type and fields

Revision ID: 72968cb7c126
Revises: dd851097ce36
Create Date: 2026-03-02 13:34:18.355986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72968cb7c126'
down_revision: Union[str, Sequence[str], None] = 'dd851097ce36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('terminal_pid', sa.Integer(), nullable=True))
    op.add_column('executions', sa.Column('terminal_command', sa.Text(), nullable=True))
    op.add_column('executions', sa.Column('terminal_cwd', sa.String(length=500), nullable=True))
    op.add_column('executions', sa.Column('terminal_output', sa.Text(), nullable=True))
    op.create_index(op.f('ix_executions_terminal_pid'), 'executions', ['terminal_pid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_executions_terminal_pid'), table_name='executions')
    op.drop_column('executions', 'terminal_output')
    op.drop_column('executions', 'terminal_cwd')
    op.drop_column('executions', 'terminal_command')
    op.drop_column('executions', 'terminal_pid')
    # ### end Alembic commands ###
