"""add_agent_framework_and_plan_models

Revision ID: a2be1393b6ef
Revises: eb7fe8d3da6d
Create Date: 2026-03-12 08:34:35.230862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2be1393b6ef'
down_revision: Union[str, Sequence[str], None] = 'eb7fe8d3da6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('template_data', sa.JSON(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('applicable_agent_types', sa.JSON(), nullable=False),
    sa.Column('applicable_frameworks', sa.JSON(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_templates'))
    )
    op.create_index(op.f('ix_plan_templates_category'), 'plan_templates', ['category'], unique=False)
    op.create_index(op.f('ix_plan_templates_id'), 'plan_templates', ['id'], unique=False)
    op.create_index(op.f('ix_plan_templates_name'), 'plan_templates', ['name'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('plan_type', sa.Enum('SEQUENTIAL', 'PARALLEL', 'CONDITIONAL', 'LOOP', 'HYBRID', name='plantype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATED', 'APPROVED', 'EXECUTING', 'COMPLETED', 'FAILED', 'CANCELLED', name='planstatus', native_enum=False), nullable=False),
    sa.Column('generated_by', sa.String(length=100), nullable=True),
    sa.Column('generation_prompt', sa.Text(), nullable=True),
    sa.Column('generation_model', sa.String(length=50), nullable=True),
    sa.Column('max_execution_time', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('completed_steps', sa.Integer(), nullable=False),
    sa.Column('failed_steps', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_step_id', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_plans_agent_id_agents')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_plans_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans'))
    )
    op.create_index(op.f('ix_plans_agent_id'), 'plans', ['agent_id'], unique=False)
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=False)
    op.create_index(op.f('ix_plans_status'), 'plans', ['status'], unique=False)
    op.create_index(op.f('ix_plans_task_id'), 'plans', ['task_id'], unique=False)
    op.create_table('plan_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_config', sa.JSON(), nullable=False),
    sa.Column('depends_on', sa.JSON(), nullable=False),
    sa.Column('parallel_group', sa.String(length=50), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('skip_on_failure', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='stepstatus', native_enum=False), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_steps_plan_id_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_steps'))
    )
    op.create_index(op.f('ix_plan_steps_id'), 'plan_steps', ['id'], unique=False)
    op.create_index(op.f('ix_plan_steps_plan_id'), 'plan_steps', ['plan_id'], unique=False)
    op.add_column('agents', sa.Column('framework', sa.Enum('CLAUDE_CODE', 'OPENCLAW', 'HYBRID', name='agentframework', native_enum=False), nullable=False))
    op.add_column('agents', sa.Column('agent_type', sa.Enum('SUBAGENT', 'SESSION', 'WORKFLOW', 'TERMINAL', name='agenttype', native_enum=False), nullable=False))
    op.add_column('agents', sa.Column('persist', sa.String(length=50), nullable=True))
    op.add_column('agents', sa.Column('context', sa.JSON(), nullable=True))
    op.add_column('agents', sa.Column('retry', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('backoff', sa.String(length=20), nullable=True))
    op.add_column('agents', sa.Column('permissions', sa.JSON(), nullable=False))
    op.add_column('agents', sa.Column('template_id', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('tags', sa.JSON(), nullable=False))
    op.add_column('agents', sa.Column('category', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_agents_agent_type'), 'agents', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agents_category'), 'agents', ['category'], unique=False)
    op.create_index(op.f('ix_agents_framework'), 'agents', ['framework'], unique=False)
    op.create_index(op.f('ix_agents_template_id'), 'agents', ['template_id'], unique=False)

    # SQLite 不支持 ALTER COLUMN TYPE，跳过此操作
    # execution_type 字段已经存在，类型差异不影响功能
    # op.alter_column('executions', 'execution_type',
    #            existing_type=sa.VARCHAR(length=10),
    #            type_=sa.Enum('WORKFLOW', 'AGENT_TEST', 'AGENT_TEAM', 'TERMINAL', 'PLAN_EXECUTION', name='executiontype', native_enum=False),
    #            existing_nullable=False)

    op.add_column('tasks', sa.Column('task_type', sa.Enum('SINGLE_AGENT', 'MULTI_AGENT', 'WORKFLOW', 'AGENT_TEAM', 'TERMINAL', 'CUSTOM', name='tasktype', native_enum=False), nullable=False))
    op.add_column('tasks', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('current_plan_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('auto_generate_plan', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('plan_template_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('input_parameters', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('execution_config', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('priority', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('execution_count', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('success_count', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('failure_count', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('result_data', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('tags', sa.JSON(), nullable=False))
    op.add_column('tasks', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tasks_agent_id'), 'tasks', ['agent_id'], unique=False)
    op.create_index(op.f('ix_tasks_category'), 'tasks', ['category'], unique=False)
    op.create_index(op.f('ix_tasks_current_plan_id'), 'tasks', ['current_plan_id'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)

    # SQLite 需要使用 batch mode 来添加外键约束
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_foreign_key(op.f('fk_tasks_agent_id_agents'), 'agents', ['agent_id'], ['id'])
        batch_op.create_foreign_key(op.f('fk_tasks_plan_template_id_plan_templates'), 'plan_templates', ['plan_template_id'], ['id'])
        batch_op.create_foreign_key(op.f('fk_tasks_current_plan_id_plans'), 'plans', ['current_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # SQLite 需要使用 batch mode 来删除外键约束
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('fk_tasks_current_plan_id_plans'), type_='foreignkey')
        batch_op.drop_constraint(op.f('fk_tasks_plan_template_id_plan_templates'), type_='foreignkey')
        batch_op.drop_constraint(op.f('fk_tasks_agent_id_agents'), type_='foreignkey')

    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_current_plan_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_category'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_agent_id'), table_name='tasks')
    op.drop_column('tasks', 'completed_at')
    op.drop_column('tasks', 'started_at')
    op.drop_column('tasks', 'category')
    op.drop_column('tasks', 'tags')
    op.drop_column('tasks', 'error_message')
    op.drop_column('tasks', 'result_data')
    op.drop_column('tasks', 'failure_count')
    op.drop_column('tasks', 'success_count')
    op.drop_column('tasks', 'execution_count')
    op.drop_column('tasks', 'deadline')
    op.drop_column('tasks', 'scheduled_at')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'execution_config')
    op.drop_column('tasks', 'input_parameters')
    op.drop_column('tasks', 'plan_template_id')
    op.drop_column('tasks', 'auto_generate_plan')
    op.drop_column('tasks', 'current_plan_id')
    op.drop_column('tasks', 'agent_id')
    op.drop_column('tasks', 'task_type')

    # SQLite 不支持 ALTER COLUMN TYPE，跳过此操作
    # op.alter_column('executions', 'execution_type',
    #            existing_type=sa.Enum('WORKFLOW', 'AGENT_TEST', 'AGENT_TEAM', 'TERMINAL', 'PLAN_EXECUTION', name='executiontype', native_enum=False),
    #            type_=sa.VARCHAR(length=10),
    #            existing_nullable=False)

    op.drop_index(op.f('ix_agents_template_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_framework'), table_name='agents')
    op.drop_index(op.f('ix_agents_category'), table_name='agents')
    op.drop_index(op.f('ix_agents_agent_type'), table_name='agents')
    op.drop_column('agents', 'category')
    op.drop_column('agents', 'tags')
    op.drop_column('agents', 'template_id')
    op.drop_column('agents', 'permissions')
    op.drop_column('agents', 'backoff')
    op.drop_column('agents', 'retry')
    op.drop_column('agents', 'context')
    op.drop_column('agents', 'persist')
    op.drop_column('agents', 'agent_type')
    op.drop_column('agents', 'framework')
    op.drop_index(op.f('ix_plan_steps_plan_id'), table_name='plan_steps')
    op.drop_index(op.f('ix_plan_steps_id'), table_name='plan_steps')
    op.drop_table('plan_steps')
    op.drop_index(op.f('ix_plans_task_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_status'), table_name='plans')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_agent_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_plan_templates_name'), table_name='plan_templates')
    op.drop_index(op.f('ix_plan_templates_id'), table_name='plan_templates')
    op.drop_index(op.f('ix_plan_templates_category'), table_name='plan_templates')
    op.drop_table('plan_templates')
    # ### end Alembic commands ###
