"""add chat_history field to execution

Revision ID: dd851097ce36
Revises: 554752830809
Create Date: 2026-03-02 02:15:37.681795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd851097ce36'
down_revision: Union[str, Sequence[str], None] = '554752830809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('chat_history', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executions', 'chat_history')
    # ### end Alembic commands ###
